### ISSUE TITLE
ServerRequest object returned to promises in context.res does not provide request body

### ISSUE THREAD

**Issue by alexjeffburke** [unexpectedjs/unexpected-express#5]
Hey,

I's using unexpected-express to assert a bunch of known values in a response, but then I wanted to attach a an extra assertion in a then() on the promise to assert an extra unknown value had been attached to the body. It seems the sanitised ServerResponse object returned does not provide the response body.

I think it occurs where the library has taken care of buffering the response bytes such that assertions can be done on them - the messy.HttpResponse() construction on line 322 seems to put those bytes back together as a breakpoint just after it shows it has an _body property which does have the response object and it has been JSON parsed. However, the httpResponse _body property is never attached to the ServerResponse that is actually returned in the context.

I think a fix could be to add extra line on after 325 that does res.body = httpResponse._body (potentially protected by an if). Does my assessment seem correct? I am happy to make a pull request if desired - my only other question is whether there are other things that should also be attached e.g. headers.

Thanks, Alex J Burke.

**Comment by papandreou** [comment]
I'm pretty sure you would be able to assert the presence of that extra unknown value using some kind of `expect.it(...)` construct, as the response body is matched with `to satisfy` semantics. If you tell me what you need to assert, I can probably help you out.

However, you should also be able to get to the response body in your `then` function, but rather than mounting extra properties on `res` I've chosen to provide a context where you get the full `messy.HttpRequest` and `messy.HttpResponse` instances as part of a context object (alongside `req` and `res`), which should give you the complete picture:

```javascript
it('should foo', function () {
    return expect(express().use(function (req, res, next) {
        res.send({ foo: 123, unknownExtraValue: 456 });
    }), 'to yield exchange', {
        response: {
            body: { foo: 123 }
        }
    }).then(function (context) {
        console.log(context.httpResponse.rawBody);
        // <Buffer 7b 22 66 6f 6f 22 3a 31 32 33 2c 22 75 6e 6b 6e 6f 77 6e 45 78 74 72 61 56 61 6c 75 65 22 3a 34 35 36 7d>

        console.log(context.httpResponse.unchunkedBody);
        // <Buffer 7b 22 66 6f 6f 22 3a 31 32 33 2c 22 75 6e 6b 6e 6f 77 6e 45 78 74 72 61 56 61 6c 75 65 22 3a 34 35 36 7d>

        console.log(context.httpResponse.body);
        // { foo: 123, unknownExtraValue: 456 }

        expect(context.httpResponse.body.unknownExtraValue, 'to equal', 456);
    });
});
```

So `context.httpResponse.body` is the nice, parsed representation of the response body, whereas `unchunkedBody` and `rawBody` are lower level representations of it.

The difference between `rawBody` and `unchunkedBody` is that when you have a `Transfer-Encoding: chunked` message, `unchunkedBody` has the chunking removed, which is what you want 99%+ of the time when you're making assertions about it.

**Comment by papandreou** [comment]
Oh, note that `unchunkedBody` was unavailable until 6.1.0, which was released about 15 minutes ago :)

**Comment by alexjeffburke** [comment]
Ahh nice. I think between the info and the unchunkedBody that's all I needed covered :)

Yeah, your code block is almost exactly what I was doing, but for posterity let me just mention the use case - I was doing a couchdb query and while I could assert that the id that came back was the one I submitted, I also wanted to check that a rev had been included in the response.

From express conventions I had assumed that the res (once I saw it was attached to the context) would have the body, but yes, it's on the httpResponse. Job done - thanks for writing that up.
